<script lang="ts">
 import ProductCard from '$lib/ProductCard.svelte'; import { formatPrice, orderEmail } from '$lib/data';
 let { data } = $props();
 const product = $derived(data.product);
 const related = $derived(data.related);
 const subject = $derived(encodeURIComponent(`Artwork inquiry: ${product.title}`));
</script>
<svelte:head><title>{product.title} — deebstore</title><meta name="description" content={`${product.title}, ${product.medium}, ${product.dimensions}. ${product.description}`} /><meta property="og:title" content={`${product.title} — deebstore`} /><meta property="og:description" content={product.description} /><meta property="og:image" content={product.image} /><meta property="og:type" content="product" /></svelte:head>
<div class="crumb"><a href="/#shop">← All work</a><span>{product.category} · {product.year}</span></div>
<section class="product"><div class="art"><img src={product.image} alt={product.alt} width="800" height="1000" /></div><div class="info"><p class="category">{product.category} · {product.year}</p><h1>{product.title}</h1><p class="price" class:sold={product.status === 'sold'}>{product.status === 'sold' ? 'Sold' : formatPrice(product)}</p><p class="description">{product.description}</p><dl><div><dt>Medium</dt><dd>{product.medium}</dd></div><div><dt>Dimensions</dt><dd>{product.dimensions}</dd></div><div><dt>Availability</dt><dd class:available={product.status === 'available'}>{product.status === 'available' ? 'Available · one of one' : 'Sold · archive'}</dd></div></dl>{#if product.status === 'available'}<a class="cta" href={`mailto:${orderEmail}?subject=${subject}`}>Inquire to purchase <span>↗</span></a><p class="note">We’ll reply with shipping costs and payment details. Local pickup may be available.</p>{:else}<a class="text-link" href="/#shop">Find available work →</a>{/if}</div></section>
{#if related.length}<section class="related"><p class="category">More {product.category.toLowerCase()}s</p><h2>You might also like</h2><div class="related-grid">{#each related as item}<ProductCard product={item} />{/each}</div></section>{/if}
<style>
 .crumb{padding:15px var(--pad) 28px;display:flex;justify-content:space-between;font-size:.68rem;text-transform:uppercase;letter-spacing:.12em}.crumb a{text-decoration:none}.crumb span{color:var(--muted)}.product{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(350px,.65fr);gap:clamp(40px,7vw,110px);padding:0 var(--pad) 110px;align-items:start}.art{background:#ddd8cc;display:grid;place-items:center;padding:clamp(18px,5vw,65px)}.art img{display:block;width:100%;max-height:75vh;object-fit:contain;filter:drop-shadow(0 12px 14px #1a18141c)}.info{position:sticky;top:40px;padding-top:45px}.category{text-transform:uppercase;letter-spacing:.16em;font-size:.65rem;color:var(--muted)}h1{font:400 clamp(3.2rem,5vw,6.2rem)/.87 var(--serif);letter-spacing:-.05em;margin:23px 0 18px}.price{font-weight:500;margin-bottom:42px}.price.sold{text-transform:uppercase;letter-spacing:.12em;font-size:.72rem;color:var(--muted)}.description{font:300 1.2rem/1.55 var(--serif);max-width:530px}dl{margin:38px 0;border-top:1px solid var(--line)}dl div{display:grid;grid-template-columns:120px 1fr;gap:20px;padding:14px 0;border-bottom:1px solid var(--line);font-size:.76rem}dt{color:var(--muted)}dd{margin:0}.available::before{content:'';display:inline-block;width:6px;height:6px;background:#477451;border-radius:50%;margin:0 8px 1px 0}.cta{display:flex;justify-content:space-between;background:var(--ink);color:var(--paper);padding:17px 19px;text-decoration:none;text-transform:uppercase;font-size:.72rem;letter-spacing:.12em}.cta:hover{background:var(--accent)}.note{font-size:.67rem;line-height:1.5;color:var(--muted)}.text-link{text-transform:uppercase;letter-spacing:.1em;font-size:.72rem}.related{padding:90px var(--pad) 120px;border-top:1px solid var(--line)}.related h2{font:400 clamp(2.5rem,4vw,4rem) var(--serif);margin:10px 0 45px}.related-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:22px}
 @media(max-width:800px){.product{grid-template-columns:1fr;padding-bottom:75px}.info{position:static;padding-top:0}.related-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:550px){.crumb{padding-top:8px}.crumb span{display:none}.art{margin:0 calc(var(--pad) * -1);padding:24px}.product{gap:32px}h1{font-size:3.5rem}.related{padding-top:70px}.related-grid{grid-template-columns:1fr}}
</style>
