<script lang="ts">
  import ProductCard from '$lib/ProductCard.svelte';
  import { products, categories, type Category } from '$lib/data';
  let category = $state<'All' | Category>('All');
  let query = $state('');
  let visible = $derived(products.filter((p) => (category === 'All' || p.category === category) && p.title.toLowerCase().includes(query.toLowerCase().trim())));
</script>
<svelte:head>
  <title>deebstore — original canvases & drawings</title>
  <meta name="description" content="Original canvases, drawings, and small art objects made by two friends. Browse available and archived work from deebstore." />
  <meta property="og:title" content="deebstore — original art, made slowly" /><meta property="og:description" content="Original canvases, drawings, and small art objects." /><meta property="og:type" content="website" /><meta property="og:image" content="/art/after-the-rain.svg" />
</svelte:head>
<section class="hero">
  <div class="hero-copy"><p class="kicker">Independent art studio · 2026 collection</p><h1>Art for rooms<br />that feel <em>lived in</em></h1><p class="intro">Original canvases, drawings, and objects made slowly by two friends. No editions. No algorithm.</p><a class="down" href="#shop">See the collection <span>↓</span></a></div>
  <div class="hero-art"><img src="/art/soft-architecture.svg" alt="Soft Architecture, an abstract canvas in ochre and black" width="800" height="1000" /><p><span>Featured work</span> Soft Architecture, 2026</p></div>
</section>
<section class="manifesto" aria-label="Our approach"><p>We make <em>one-of-one</em> work with tactile surfaces, wonky lines, and evidence of the hand</p><span class="scribble" aria-hidden="true">✳</span></section>
<section class="catalogue" id="shop">
  <div class="section-head"><div><p class="kicker">The catalogue</p><h2>Available & archived work</h2></div><label class="search"><span class="sr-only">Search artworks</span><input bind:value={query} type="search" placeholder="Search by title" aria-label="Search artworks" /><span>⌕</span></label></div>
  <div class="filters" aria-label="Filter by category"><button class:active={category === 'All'} onclick={() => category = 'All'}>All <sup>{products.length}</sup></button>{#each categories as item}<button class:active={category === item} onclick={() => category = item}>{item} <sup>{products.filter(p => p.category === item).length}</sup></button>{/each}</div>
  {#if visible.length}<div class="grid">{#each visible as product (product.slug)}<ProductCard {product} />{/each}</div>{:else}<div class="empty"><p>No work found under “{query}”</p><button onclick={() => {query=''; category='All'}}>Clear search</button></div>{/if}
</section>
<section class="about" id="about"><div class="about-mark">d<span>²</span></div><div><p class="kicker">Behind deebstore</p><h2>Two friends, one shared habit of making things</h2><p>deebstore is an independent art project built around curiosity, material, and the belief that original art should feel personal rather than precious. Every piece passes through our hands, from first mark to final wrapping.</p><a href="mailto:hello@deebstore.art">Talk to us about a piece →</a></div></section>
<style>
  .hero{min-height:calc(100vh - 84px);padding:45px var(--pad) 70px;display:grid;grid-template-columns:1.05fr .75fr;gap:8vw;align-items:center}.kicker{text-transform:uppercase;letter-spacing:.16em;font-size:.64rem;font-weight:500;margin:0 0 24px}.hero h1{font:300 clamp(3.5rem,7.5vw,8.2rem)/.84 var(--serif);letter-spacing:-.055em;margin:0}.hero h1 em{font-weight:300;color:var(--accent)}.intro{max-width:430px;margin:34px 0;color:var(--muted);font:300 1.03rem/1.6 var(--sans)}.down{display:inline-flex;gap:28px;font-size:.76rem;text-transform:uppercase;letter-spacing:.12em;text-decoration:none;border-bottom:1px solid;padding-bottom:7px}.down span{font-size:1rem}.hero-art{align-self:stretch;display:flex;flex-direction:column;justify-content:center}.hero-art img{width:100%;max-height:68vh;object-fit:cover}.hero-art p{font-size:.7rem;display:flex;justify-content:space-between;margin:10px 0}.hero-art p span{color:var(--muted)}.manifesto{background:#202d28;color:#f2f0e9;padding:100px var(--pad);position:relative}.manifesto p{font:300 clamp(2.5rem,5vw,5.2rem)/1.05 var(--serif);max-width:1100px;margin:0;letter-spacing:-.025em}.manifesto em{color:#e39d75}.scribble{position:absolute;right:8%;bottom:12%;font-size:4rem;color:#e39d75;transform:rotate(14deg)}.catalogue{padding:110px var(--pad)}.section-head{display:flex;align-items:end;justify-content:space-between;gap:30px}.section-head h2,.about h2{font:400 clamp(2.5rem,4.5vw,4.7rem)/.95 var(--serif);letter-spacing:-.04em;margin:0}.search{border-bottom:1px solid var(--ink);display:flex;align-items:center;min-width:210px}.search input{border:0;background:transparent;outline:0;padding:10px 0;width:100%;font-size:.8rem}.filters{display:flex;gap:8px;margin:48px 0 28px;flex-wrap:wrap}.filters button{background:transparent;border:1px solid var(--line);border-radius:30px;padding:9px 16px;cursor:pointer;font-size:.74rem}.filters button.active{background:var(--ink);border-color:var(--ink);color:var(--paper)}.filters sup{margin-left:5px;color:inherit;opacity:.6}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:50px 22px}.empty{padding:100px 20px;text-align:center;border:1px solid var(--line)}.empty p{font:2rem var(--serif)}.empty button{border:0;border-bottom:1px solid;background:none;padding:6px;cursor:pointer}.about{padding:110px var(--pad);display:grid;grid-template-columns:1fr 1.2fr;gap:8vw;border-top:1px solid var(--line);align-items:center}.about-mark{width:min(28vw,350px);aspect-ratio:1;background:#b7482c;color:#f2f0e9;display:grid;place-content:center;font:300 8rem var(--serif);transform:rotate(-3deg)}.about-mark span{font-size:3rem}.about>div:last-child>p:not(.kicker){line-height:1.7;color:var(--muted);max-width:590px;margin:28px 0}.about a{font-size:.8rem;text-transform:uppercase;letter-spacing:.1em}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}
  @media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}.hero{gap:5vw}.about{grid-template-columns:.7fr 1.3fr}}
  @media(max-width:700px){.hero{min-height:auto;padding-top:35px;grid-template-columns:1fr}.hero h1{font-size:clamp(3.5rem,17vw,5.2rem)}.hero-art{margin-top:24px}.hero-art img{height:55vh}.manifesto{padding:70px var(--pad)}.scribble{font-size:2rem}.catalogue{padding-top:75px;padding-bottom:75px}.section-head{align-items:start;flex-direction:column}.search{width:100%}.filters{margin-top:34px}.grid{grid-template-columns:1fr;gap:45px}.about{grid-template-columns:1fr;padding-top:75px;padding-bottom:75px}.about-mark{width:65vw;max-width:280px}.about h2{font-size:2.7rem}}
</style>
